security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Digiclic\FrontArchiveMediaBundle\Providers\Client: 
            algorithm:           sha1
            encode_as_base64:    false
            iterations:          1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        clients:
            id: client_provider


    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # the login page has to be accessible for everybody
        login:
            pattern:  ^/login$
            security: false

        # secures part of the application
        secured_area:
            pattern:    ^/
            form_login:
                check_path: security_check
                login_path: login
            logout:
                path:   _demo_logout
                target: _demo

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
