db:
    image: mongo
    volumes:
        - ./db:/data/db   
    command: --smallfiles

clients:
    build: ./clients
    links:
       - db
    ###DEV
    ports:
       - "81:80"
    volumes:
        - ./clients/app:/root/app

front:
    build: ./front
    ports:
       - "80:80"
    links:
       - clients 
    ###DEV
    volumes:
        - ./front/front:/root/symfony
        
#search:
#    build: ./search
#
#share:
#    build: ./share
#
